<?php
/**
 * Auto generated from hangouts.proto at 2017-02-10 13:29:52
 */

namespace {
/**
 * ConfigurationBitType enum
 */
final class ConfigurationBitType
{
    const CONFIGURATION_BIT_TYPE_UNKNOWN = 0;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_1 = 1;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_2 = 2;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_3 = 3;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_4 = 4;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_5 = 5;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_6 = 6;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_7 = 7;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_8 = 8;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_9 = 9;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_10 = 10;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_11 = 11;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_12 = 12;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_13 = 13;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_14 = 14;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_15 = 15;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_16 = 16;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_17 = 17;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_18 = 18;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_19 = 19;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_20 = 20;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_21 = 21;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_22 = 22;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_23 = 23;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_24 = 24;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_25 = 25;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_26 = 26;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_27 = 27;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_28 = 28;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_29 = 29;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_30 = 30;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_31 = 31;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_32 = 32;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_33 = 33;
    const CONFIGURATION_BIT_TYPE_DESKTOP_AUTO_EMOJI_CONVERSION_ENABLED = 34;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_35 = 35;
    const CONFIGURATION_BIT_TYPE_UNKNOWN_36 = 36;
    const CONFIGURATION_BIT_TYPE_DESKTOP_COMPACT_MODE_ENABLED = 38;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'CONFIGURATION_BIT_TYPE_UNKNOWN' => self::CONFIGURATION_BIT_TYPE_UNKNOWN,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_1' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_1,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_2' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_2,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_3' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_3,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_4' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_4,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_5' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_5,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_6' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_6,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_7' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_7,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_8' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_8,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_9' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_9,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_10' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_10,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_11' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_11,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_12' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_12,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_13' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_13,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_14' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_14,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_15' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_15,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_16' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_16,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_17' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_17,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_18' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_18,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_19' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_19,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_20' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_20,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_21' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_21,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_22' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_22,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_23' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_23,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_24' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_24,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_25' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_25,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_26' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_26,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_27' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_27,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_28' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_28,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_29' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_29,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_30' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_30,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_31' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_31,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_32' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_32,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_33' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_33,
            'CONFIGURATION_BIT_TYPE_DESKTOP_AUTO_EMOJI_CONVERSION_ENABLED' => self::CONFIGURATION_BIT_TYPE_DESKTOP_AUTO_EMOJI_CONVERSION_ENABLED,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_35' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_35,
            'CONFIGURATION_BIT_TYPE_UNKNOWN_36' => self::CONFIGURATION_BIT_TYPE_UNKNOWN_36,
            'CONFIGURATION_BIT_TYPE_DESKTOP_COMPACT_MODE_ENABLED' => self::CONFIGURATION_BIT_TYPE_DESKTOP_COMPACT_MODE_ENABLED,
        );
    }
}
}